apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spacelift-worker

# We're using a kustomization.yaml file here so that we can specify the resources to load.
# That prevents kustomize from picking up the values.yaml file.
resources:
- spacelift-worker-pool.yaml
